# Generated by Django 4.2.10 on 2024-03-03 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commissions",
            fields=[
                (
                    "_id_commissions",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("date", models.DateTimeField(default=datetime.datetime.today)),
                ("foliate_commission", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "_id_teacher",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("email1", models.EmailField(max_length=20, unique=True)),
                ("email2", models.EmailField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("S", "sended"), ("F", "fail"), ("P", "pending")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("foliate_teacher", models.CharField(max_length=20, unique=True)),
                ("path_pdf", models.FilePathField(unique=True)),
                (
                    "_id_commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codo_app.commissions",
                    ),
                ),
                (
                    "_id_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codo_app.teachers",
                    ),
                ),
            ],
        ),
    ]
