# Generated by Django 5.0.3 on 2024-03-06 21:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id_commissions', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('foliate_commission', models.CharField(max_length=20)),
                ('pdf_master', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email1', models.EmailField(max_length=20, unique=True)),
                ('email2', models.EmailField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id_commission', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('S', 'sended'), ('F', 'fail'), ('P', 'pending')], default='P', max_length=1)),
                ('foliate_teacher', models.CharField(max_length=20, unique=True)),
                ('path_pdf', models.FileField(blank=True, unique=True, upload_to='files')),
                ('_id_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codo_app.commissions')),
                ('_id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codo_app.teachers')),
            ],
        ),
    ]
