# Generated by Django 4.2.10 on 2024-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissions",
            name="_id_commissions",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="_id_teacher",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
