# Generated by Django 4.2.10 on 2024-03-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codo_app", "0002_alter_commissions__id_commissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachers",
            name="email2",
            field=models.EmailField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
