# Generated by Django 4.2.10 on 2024-03-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codo_app", "0003_alter_teachers_email2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="path_pdf",
            field=models.FilePathField(blank=True, unique=True),
        ),
    ]
