# Generated by Django 4.2.10 on 2024-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codo_app", "0005_alter_commission_foliate_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="foliate_teacher",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="commission",
            name="path_pdf",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
