# Generated by Django 4.2.10 on 2024-03-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codo_app", "0006_alter_commission_foliate_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissions",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
